workouts:
  # upper body 
  pull:
    exercises:
      - name: pullup
        track_rest: true
        metrics:
          - reps

  push:
      - name: dip
        track_rest: true
        metrics:
          - reps
      - name: pike_pushup
        metrics:
          - reps
      - name: press
        metrics:
          - reps
          - weight


  frontsplit:
    exercises:
      - name: wide_split_squat
        metrics:
          - reps
          - thigh2floor

  lower:
    exercises:
      - name: cossack_squat
        metrics:
          - reps
          - weight
      - name: shrimp
        metrics:
          - reps
          - knee2floor
      - name: stride_stance_deadlift
        metrics:
          - reps
          - weight

  handstand:
    exercises:
      - name: bridge
        metrics:
          - time
          - feet2floor
      - name: chest2wall
        metrics:
          - time

  home:
    exercises:
      - name: rice_bucket
        metrics:
          - time
      - name: squat2sissy
        metrics:
          - reps
          - feet2floor
      - name: heel_elevation
        metrics:
          - reps
          - weight
      - name: towel_roll
        metrics:
          - reps
          - weight
